import assert from "node:assert/strict";
import { readFile, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { DatabaseSync } from "node:sqlite";
import { chromium } from "playwright";

const run = process.argv[2];
assert.match(run || "", /^p0p1-m1-[A-Za-z0-9_-]+$/);
const root = path.resolve("output", run, "paper-test");
const out = path.resolve("docs/verification/p0p1/M1");
await mkdir(out, { recursive: true });
const browser = await chromium.connectOverCDP("http://127.0.0.1:9254");
const getPages = () => browser.contexts().flatMap((context) => context.pages());
const workbench = () => getPages().find((page) => page.url().includes("workbench=1"));
const paper = () => getPages().find((page) => page.url() === "http://tauri.localhost/");
assert(workbench() && paper(), "Real native Paper and workbench WebViews required");
const invoke = (command, args = {}) => workbench().evaluate(({ command, args }) => window.__TAURI_INTERNALS__.invoke(command, args), { command, args });
assert.equal(path.resolve((await invoke("get_paper_bridge_status")).connectionFile), path.join(root, "paper-agent-bridge.json"));
const api = (action, input = {}) => invoke("paper_execute", { action, input: { ...input, ...(action.startsWith("get_") ? {} : { requestId: randomUUID() }) } });
const state = async () => (await api("get_state")).state;
const key = (d = new Date()) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const shift = (n) => { const d = new Date(); d.setDate(d.getDate()+n); return key(d); };
const today = key(), yesterday = shift(-1), tomorrow = shift(1);
const checks = [], errors = [];
for (const page of getPages()) { page.setDefaultTimeout(15000); page.on("pageerror", (error) => errors.push(error.message)); }
const pass = (message) => { checks.push(message); console.log("PASS", message); };

try {
  const fixture = JSON.parse(await readFile("scripts/fixtures/p0p1/legacy-state.json", "utf8"));
  const current = await state();
  assert.deepEqual(current.sessions, fixture.state.sessions);
  const backup = new DatabaseSync(path.join(root,"paper.sqlite3.pre-schema-1.sqlite"),{readOnly:true});
  assert.equal(backup.prepare("PRAGMA user_version").get().user_version,0);
  assert.deepEqual(JSON.parse(backup.prepare("SELECT data FROM paper_state WHERE id=1").get().data),fixture.state);
  backup.close();
  const db = new DatabaseSync(path.join(root,"paper.sqlite3"),{readOnly:true});
  assert.equal(db.prepare("PRAGMA user_version").get().user_version,1); db.close();
  pass("Native startup migrated the synthetic legacy database with a verified v0 backup and unchanged session snapshots");
  assert.equal(current.tasks.length, fixture.state.tasks.length, "Use a fresh M1 run");
  const create = (title,text,date,more={}) => api("workbench_save_step",{taskId:randomUUID(),stepId:randomUUID(),title,text,category:"work",plannedSeconds:900,date,...more});
  const old = await create("M1 遗留合成任务","继续昨天的一步",yesterday);
  const first = await create("M1 今日合成任务","今日第一步",today,{priority:"high",due:"等对方确认",dueDate:tomorrow,expectedResult:"两项结果可核对"});
  const second = await api("workbench_save_step",{taskId:first.task.id,stepId:randomUUID(),expectedTaskRevision:first.task.revision,title:first.task.title,text:"今日第二步",category:"work",plannedSeconds:1200,date:today});
  const future = await create("M1 未来合成任务","提前执行未来步骤",tomorrow);
  const loose = await create("M1 临时合成任务","未安排的临时工作",null);
  const rescheduled = await create("M1 已改期合成任务","已有未来安排",yesterday);
  await api("workbench_save_step",{taskId:rescheduled.task.id,stepId:rescheduled.step.id,expectedTaskRevision:1,expectedStepRevision:1,title:rescheduled.task.title,text:rescheduled.step.text,category:"work",plannedSeconds:900,date:tomorrow});
  await writeFile(path.resolve("output",run,"seed.json"),JSON.stringify({today,yesterday,tomorrow,old,first,second,future,loose,rescheduled},null,2));
  pass("Synthetic old, today, future, unplanned and already-rescheduled steps created through named operations");
  await invoke("coach_show_main",{view:"home"});
  await paper().getByRole("button",{name:"今天",exact:true}).waitFor();
  await paper().getByText("今日第一步",{exact:true}).first().waitFor();
  await paper().getByText("今日第二步",{exact:true}).first().waitFor();
  await paper().screenshot({path:path.join(out,"today-queue.png")});
  await workbench().screenshot({path:path.join(out,"workbench.png")});
  pass("Paper shows both planned steps of one task in the real native window");
  const queueIds = () => paper().locator(".sheet-queue-item[data-plan-item-id]").evaluateAll((nodes) => nodes.map((node) => node.dataset.planItemId));
  assert.deepEqual(await queueIds(), [first.item.id, second.item.id]);
  await paper().getByRole("button",{name:"完成步骤：今日第一步",exact:true}).click();
  await paper().getByRole("button",{name:"撤销步骤完成：今日第一步",exact:true}).waitFor();
  assert.deepEqual(await queueIds(), [first.item.id, second.item.id]);
  let snapshot=await state();
  assert.equal(snapshot.tasks.find((task)=>task.id===first.task.id).completed,false);
  assert.equal(snapshot.sessions.length,fixture.state.sessions.length);
  assert.equal(snapshot.planning.manualStepChanges.at(-1).completed,true);
  await paper().getByRole("button",{name:"撤销步骤完成：今日第一步",exact:true}).click();
  await paper().getByRole("button",{name:"完成步骤：今日第一步",exact:true}).waitFor();
  pass("Manual step completion and undo retain queue position, keep the parent pending and create no clock");
  await workbench().locator(".wk-leftovers > summary").click();
  const oldGroup=workbench().locator(".wk-leftover-group").filter({hasText:"继续昨天的一步"});
  const movedGroup=workbench().locator(".wk-leftover-group").filter({hasText:"已有未来安排"});
  assert.match(await movedGroup.innerText(),/已重新安排/);
  assert.equal(await movedGroup.evaluate(node=>node.open),false);
  await oldGroup.locator("summary").click();
  await oldGroup.getByRole("button",{name:"今天继续",exact:true}).click();
  await workbench().getByText("已安排今天继续，保留同一步骤和原有记录。",{exact:true}).waitFor();
  snapshot=await state();
  const oldPlans=snapshot.planning.dayItems.filter(item=>item.stepId===old.step.id);
  assert.equal(oldPlans.length,2);
  const continued=oldPlans.find(item=>item.date===today);
  assert(continued);
  assert.equal(oldPlans.find(item=>item.id===old.item.id).continuedTo,continued.id);
  assert.equal(snapshot.tasks.filter(task=>task.id===old.task.id).length,1);
  await paper().locator(`[data-plan-item-id="${continued.id}"]`).waitFor();
  const row=workbench().locator(`[data-row-id="${continued.id}"]`);
  await row.getByRole("button",{name:"放回待安排",exact:true}).click();
  const cancel=workbench().getByRole("dialog");
  assert.equal(await cancel.getByLabel("将取消的安排").locator("li").count(),2);
  await cancel.getByRole("button",{name:"确认取消 2 条安排",exact:true}).click();
  await cancel.waitFor({state:"hidden"});
  snapshot=await state();
  assert(snapshot.planning.dayItems.filter(item=>item.stepId===old.step.id).every(item=>item.removedAt!==null));
  assert.equal(snapshot.planning.steps.find(step=>step.id===old.step.id).completed,false);
  pass("Collapsed leftovers distinguish already-rescheduled steps; continue reuses the step and unplan previews/cancels the complete unexecuted set");
  await workbench().getByRole("button",{name:"修改 今日第一步",exact:true}).click();
  const editor=workbench().getByRole("dialog");
  assert.equal(await editor.getByLabel("优先级",{exact:true}).inputValue(),"high");
  assert.equal(await editor.getByLabel("安排日期",{exact:true}).inputValue(),today);
  assert.equal(await editor.getByLabel("截止日期",{exact:true}).inputValue(),tomorrow);
  assert.equal(await editor.getByLabel("截止备注",{exact:true}).inputValue(),"等对方确认");
  assert.equal(await editor.getByLabel("步骤完成标准",{exact:true}).inputValue(),"两项结果可核对");
  await editor.getByLabel("优先级",{exact:true}).selectOption("low");
  await editor.getByLabel("步骤完成标准",{exact:true}).fill("保留两条可核对结果");
  await editor.getByRole("button",{name:"保存计划",exact:true}).click();
  await editor.waitFor({state:"hidden"});
  snapshot=await state();
  assert.equal(snapshot.tasks.find(task=>task.id===first.task.id).dueDate,tomorrow);
  assert.equal(snapshot.planning.dayItems.find(item=>item.id===first.item.id).date,today);
  pass("Native editor keeps deadline, free-text due note and arrangement date separate while sharing priority and completion criteria");
  await workbench().getByRole("button",{name:"提前执行未来步骤",exact:true}).click();
  await workbench().getByRole("button",{name:"设为下一步并回到 Inky",exact:true}).click();
  await paper().locator(".next-card h2").filter({hasText:"提前执行未来步骤"}).waitFor();
  snapshot=await state();
  assert.equal(snapshot.sessions.length,fixture.state.sessions.length);
  assert.equal(snapshot.planning.prepared.dayItemId,future.item.id);
  await paper().getByRole("button",{name:"start",exact:true}).click();
  await paper().getByRole("button",{name:"返回任务列表",exact:true}).first().waitFor();
  snapshot=await state();
  const session=snapshot.sessions.find((s)=>s.status!=="finished");
  assert(session);
  assert.equal(session.action.id,future.step.id);
  assert.equal(snapshot.planning.sessionLinks.find((link)=>link.sessionId===session.id).planDate,tomorrow);
  assert.equal(key(new Date(session.startedAt)),today);
  await paper().getByRole("button",{name:"返回任务列表",exact:true}).first().click();
  assert.equal((await state()).sessions.find((s)=>s.id===session.id).status,"running");
  const target=(await state()).tasks.find((task)=>task.id===first.task.id);
  const targetStep=(await state()).planning.steps.find(step=>step.id===first.step.id);
  await assert.rejects(invoke("workbench_prepare_step",{input:{requestId:randomUUID(),taskId:target.id,stepId:first.step.id,expectedRevision:target.revision,expectedStepRevision:targetStep.revision},itemId:first.item.id}),/本轮|ACTIVE_SESSION/);
  await paper().getByRole("button",{name:"返回番茄钟",exact:true}).click();
  await paper().getByRole("button",{name:"结束番茄钟",exact:true}).click();
  await paper().getByRole("button",{name:"保存并结束",exact:true}).click();
  await paper().getByRole("button",{name:"今天",exact:true}).waitFor();
  snapshot=await state();
  const finished=snapshot.sessions.find((s)=>s.id===session.id);
  assert.equal(finished.status,"finished");
  assert.equal(finished.feedback.output,null);
  assert.equal(finished.feedback.nextCue,null);
  assert.equal(snapshot.planning.steps.find((step)=>step.id===future.step.id).completed,false);
  pass("Native handoff prepares without timing; explicit start records future plan origin, navigation preserves clock, active handoff is rejected and empty feedback saves");
  const daily=await api("get_daily_record",{date:today,utcOffsetMinutes:-new Date().getTimezoneOffset()});
  const actual=daily.sessions.find((s)=>s.id===session.id);
  assert.equal(actual.planDate,tomorrow);
  assert(daily.manualStepChanges.some((change)=>change.stepId===first.step.id));
  const markdown=await readFile(path.join(root,"工作记录/每日",`${today}.md`),"utf8");
  assert.match(markdown,/提前执行未来步骤/);
  assert.match(markdown,/手动步骤记录/);
  pass("Actual execution and manual completion facts return to the correct daily record and generated Markdown");
  await writeFile(path.resolve("output",run,"restart-expectation.json"),JSON.stringify({taskId:future.task.id,stepId:future.step.id,dayItemId:future.item.id,planDate:tomorrow,sessionId:session.id},null,2));
  assert.deepEqual(errors,[]);
} finally {
  await writeFile(path.join(out,"desktop-partial.json"),JSON.stringify({run,today,checks,errors,complete:false,modelCalls:0},null,2));
  await browser.close();
}
